### PR TITLE
fix(Pagination): add conditions for 2 siblings edge case

### LINKED ISSUE #970: [Bug]: Pagination hides a single page behind an ellipsis
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://stackblitz.com/edit/xbu9yg?file=src%2FApp.vue

### Steps to reproduce

PaginationRoot settings: `<PaginationRoot :total="90" :sibling-count="2" show-edges>`

Navigate between pages to notice the behavior.

### Describe the bug

In the example, pages 2 and 8 depending on proximity to current page get replaced with ellipsis (...) which could be always shown as page numbers since the ellipsis in this case do not conserve any space.

### Expected behavior

Show the page number instead of ellipsis if it replaces only a single page number.

### Context & Screenshots (if applicable)

image

image

image

### PR DESCRIPTION
**Pull request by epr3**
Fixes #970.

### CODE REVIEW

File: packages/radix-vue/src/Pagination/utils.ts [hunk 1]
```diff
@@ -41,18 +38,37 @@ export function getRange(currentPage: number, pageCount: number, siblingCount: n
 
     const itemCount = totalPageNumbers - 2 // 2 stands for one ellipsis and either first or last page
 
+    const showLeftEllipsis
+      // default condition
+      = leftSiblingIndex > firstPageIndex + 2
+      // if the current page is towards the end of the list
+      && lastPageIndex - itemCount - firstPageIndex + 1 > 2
+      // if the current page is towards the middle of the list
+      && leftSiblingIndex - firstPageIndex > 2
```
Comment (zernonia) [inline packages/radix-vue/src/Pagination/utils.ts:47]: Haven't test this out, but the inequality seems like the same as line 43 `leftSiblingIndex > firstPageIndex + 2`

Comment (epr3) [reply packages/radix-vue/src/Pagination/utils.ts]: Yep, my mistake, I adjusted the condition and added `Math.abs` to all calculations to make sure the conditions are always evaluated properly.

**Review by zernonia — APPROVED** [review]
LGTM!! 🚀
