### PR TITLE
fix(DateField): rebuild focusable element Set on locale change

### LINKED ISSUE #1127: [Bug]: Date Field does not update field focus order when locale changes
### Environment

```bash
Developement/Production OS: Arch Linux 6.9.8-arch1-1
Node version: 22.1.0
Package manager: pnpm@9.4.0
Radix Vue version: 1.8.3-1.9.1
Vue version: 3.4.31
Nuxt version: N/A
Nuxt mode: N/A
Nuxt target: N/A
CSS framework: N/A
Client OS: Arch Linux 6.9.8-arch1-1
Browser: Chromium 126.0.6478.126
```

### Link to minimal reproduction

https://stackblitz.com/edit/p814hu?file=src%2FApp.vue

### Steps to reproduce

- Try to input a date, such as `14/07/1789` (dd/mm/yyyy format)
- Change the locale
- Try to input another date

### Describe the bug

The focus order is still the one of the locale the component was mounted with

### Expected behavior

The focus order should properly be changed reflecting the new language (and layout)

### Context & Screenshots (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by epr3**
Fixes #1127.

### CODE REVIEW

File: packages/radix-vue/src/DateField/DateFieldRoot.vue [hunk 1]
```diff
@@ -179,8 +179,15 @@ const segmentContents = computed(() => allSegmentContent.value.arr)
...
 
 watch(locale, (value) => {
-  if (formatter.getLocale() !== value)
+  if (formatter.getLocale() !== value) {
     formatter.setLocale(value)
+    // Locale changed, so we need to clear the segment elements and re-get them (different order)
+    // Get the focusable elements again on the next tick
+    nextTick(() => {
+      segmentElements.value.clear()
+      Array.from(parentElement.value.querySelectorAll('[data-radix-vue-date-field-segment]')).filter(item => item.getAttribute('data-radix-vue-date-field-segment') !== 'literal').forEach(el => segmentElements.value.add(el as HTMLElement))
```
Comment (zernonia) [inline packages/radix-vue/src/DateField/DateFieldRoot.vue:188]: Let's wrap this as a function so that we call the same function during `onMounted` hook

File: packages/radix-vue/src/DateRangeField/DateRangeFieldRoot.vue [hunk 2]
```diff
@@ -264,8 +264,15 @@ watch([startValue, locale], ([_startValue]) => {
...
 
 watch(locale, (value) => {
-  if (formatter.getLocale() !== value)
+  if (formatter.getLocale() !== value) {
     formatter.setLocale(value)
+    // Locale changed, so we need to clear the segment elements and re-get them (different order)
+    // Get the focusable elements again on the next tick
+    nextTick(() => {
+      segmentElements.value.clear()
+      Array.from(parentElement.value.querySelectorAll('[data-radix-vue-date-field-segment]')).filter(item => item.getAttribute('data-radix-vue-date-field-segment') !== 'literal').forEach(el => segmentElements.value.add(el as HTMLElement))
```
Comment (zernonia) [inline packages/radix-vue/src/DateRangeField/DateRangeFieldRoot.vue:273]: Same here 😁

**Review by zernonia — APPROVED** [review]
LGTM! 🚀
